services:
  sql:
    image: ${SQLSERVER_IMAGE:-mcr.microsoft.com/azure-sql-edge}
    container_name: onecore-sql
    platform: ${DOCKER_SQL_PLATFORM:-}
    user: ${DOCKER_SQL_USER:-}
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=s3cr3t_p455w0rd
    networks:
      - onecore
    ports:
      - '1438:1433'
    volumes:
      - sql:/var/opt/mssql

  elasticsearch:
    container_name: onecore-elasticsearch
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    networks:
      - onecore
    ports:
      - 9208:9200
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: onecore-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    image: docker.elastic.co/kibana/kibana:8.4.1
    networks:
      - onecore
    ports:
      - 5608:5601

networks:
  onecore:
    driver: bridge

volumes:
  sql:
  elasticsearch:
